### ISSUE TITLE
Can't we use .md files instead of .xlsx files

### ISSUE THREAD

**Issue by FunctionalMetatable** [The64thCucumber/5th-suggestions-directory#1]
its easier + we dont need to keep uploading excel files

**Comment by The64thCucumber** [comment]
how is it easier

**Comment by FunctionalMetatable** [comment]
Bc we don't need to keep downloading xlsx files and uploading +nvm now

**Comment by The64thCucumber** [comment]
Ok I just converted them to .md and .csv, will upload them now
