### ISSUE TITLE
question

### ISSUE THREAD

**Issue by leahcimto** [The64thCucumber/5th-suggestions-directory#4]
what exactly are tags

**Comment by Basic8** [comment]
What do you mean by "tags"? (I'm new to GitHub)

**Comment by leahcimto** [comment]
<img width="478" alt="Screen Shot 2021-03-01 at 12 44 19 PM" src="https://user-images.githubusercontent.com/68165163/109536632-f71f5280-7a8b-11eb-9329-50bff1363fbe.png">

**Comment by Basic8** [comment]
Oh, ask fdreerf on his SCRATCH profile.
