### ISSUE TITLE
6th suggestions directory 

### ISSUE THREAD

**Issue by derter-menter** [The64thCucumber/5th-suggestions-directory#6]
Since you have all the excel sheets attached and this is inactive, am I allowed to get people to contribute (writing descriptions etc) on the 6th directory here or shall I make my own respiratory for the 6th version.

I understand if you want this to be about the 5th version but it may just be a bit more convenient for me since I am a noob with GitHub lol

thanks

**Comment by The64thCucumber** [comment]
Sure, you can use this for the 6th if that's more convenient

**Comment by derter-menter** [comment]
Thanks!
